services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    container_name: redis
    command: redis-server --port 6380
    ports:
      - '6380:6380'
